---
# - name: apt update cache
#   ansible.builtin.apt:
#     update_cache: true
#     cache_valid_time: 3600 # 1 hr
#     force_apt_get: true # aptitude may not be installed
#   become: true

- name: create application directory {{ app_directory }}
  ansible.builtin.file:
    path: "{{ app_directory }}"
    state: directory
    owner: "{{ raspi_user }}"
    group: "{{ raspi_user }}"
    recurse: true
  become: true

- name: deploy application {{ app_directory }}
  ansible.builtin.copy:
    src:   "{{ app_local_path }}/"
    dest:  "{{ app_directory }}"
    force: true
    local_follow: false

- name: docker pull latest elgeeko/pimp-my-gimp:{{ pimp_my_gimp_docker_tag }}
  community.general.docker_image:
    name: elgeeko/pimp-my-gimp:{{ pimp_my_gimp_docker_tag }}
    source: pull
    force_source: true
