galaxy_info:
  role_name: elgeeko1-pimp-my-gimp-ansible
  author: elgeeko1
  description: "Deploy the application Pimp-my-Gimp to a preconfigured Raspberry Pi"
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
collections:
  - community.docker
  - community.general
  - ansible.utils
  - ansible.posix