---
- name: add user {{ piuser }} to password-less sudousers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ piuser }} ALL=(ALL) NOPASSWD: ALL"
  become: true

- name: add user {{ piuser }} to group systemd-journal
  ansible.builtin.user:
    name: "{{ piuser }}"
    groups: systemd-journal
    append: true
  become: true

- name: add user {{ piuser }} to IO groups
  ansible.builtin.user:
    name: "{{ piuser }}"
    groups:
      - dialout
      - tty
      - bluetooth
      - kmem
      - i2c
      - kvm # /dev/udmabuf
    append: true
  become: true
