---
- name: apt install python3-venv
  ansible.builtin.apt:
    name: python3-venv
    state: latest
  become: true

- name: pip install Raspberry pi GPIO
  ansible.builtin.pip:
    name:
      - RPi.GPIO
      - rpi-ws281x  # WS281 LEDs
    state: latest
  become: true

- name: apt install GPIO features
  ansible.builtin.apt:
    name:
      - i2c-tools
      - libgpiod-dev
    state: latest
  become: true

- name: pip install adafruit-circuitpython-neopixel
  ansible.builtin.pip:
    name: adafruit-circuitpython-neopixel
    state: latest
  become: true

- name: Copy systemd service file to server
  ansible.builtin.copy:
    src: scoot.service
    dest: /etc/systemd/system
    owner: root
    group: root
  become: true

- name: Start systemd service
  ansible.builtin.systemd:
    name: scoot
    state: started
    enabled: true
  become: true

# add gimp user to systemd-journal group
# copy run.sh