---
- name: add user {{ raspi_user }} to password-less sudousers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ raspi_user }} ALL=(ALL) NOPASSWD: ALL"
  become: true

- name: add user {{ raspi_user }} to group systemd-journal
  ansible.builtin.user:
    name: "{{ raspi_user }}"
    groups: systemd-journal
    append: true
  become: true

- name: add user {{ raspi_user }} to IO groups
  ansible.builtin.user:
    name: "{{ raspi_user }}"
    groups:
      - dialout
      - tty
      - bluetooth
      - kmem
      - i2c
      - kvm # /dev/udmabuf
      - audio
    append: true
  become: true
  
- name: add local SSH identity as an authorized key
  ansible.posix.authorized_key:
    user: "{{ raspi_user }}"
    key:  "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  become: true
