galaxy_info:
  role_name: pimp-my-gimp-deploy
  author: elgeeko1
  description: "Deploy the pimp-my-gimp application to a Raspberry Pi"
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
collections:
  - community.docker
  - community.general
  - ansible.utils
  - ansible.posix
