galaxy_info:
  role_name: elgeeko1-raspi-init-ansible
  author: elgeeko1
  description: "Configure a Raspberry Pi 4 running a factory-fresh Ubuntu image"
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
collections:
  - community.docker
  - community.general
  - community.crypto
  - ansible.utils
  - ansible.posix

