galaxy_info:
  role_name: elgeeko1-pimp-my-gimp-provision-ansible
  author: elgeeko1
  description: "Provision a Raspberry Pi for controlling a dope scooter."
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
collections:
  - community.docker
  - community.general
  - ansible.utils
  - ansible.posix
dependencies:
  # - src: https://github.com/elgeeko1/elgeeko1-ubuntu-common-ansible
  #   name: elgeeko1-ubuntu-common-ansible
  #   version: main

  # - src: https://github.com/elgeeko1/elgeeko1-docker-ansible
  #   name: elgeeko1-docker-ansible
  #   version: main