---
- name: pimp-my-gimp
  hosts: scoot
  gather_facts: true
  roles:
    - name: Scoot
      role: elgeeko1-pimp-my-gimp-ansible

  tasks:
    - name: Check internet connectivity
      ansible.builtin.wait_for:
        host: google.com
        port: 80
        timeout: 10

    - name: Add local SSH identity as an authorized key
      ansible.posix.authorized_key:
        user: "{{ gimp_user }}"
        key:  "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      become: true

    - name: Remove default user ubuntu
      ansible.builtin.user:
        user: ubuntu
        state: absent
      become: true
      when: ansible_user != "ubuntu"
