---
- name: set hostname {{ raspi_host }}
  ansible.builtin.hostname:
    name: "{{ raspi_hostname }}"
  become: true
  register: hostname

- name: reboot to apply hostname
  ansible.builtin.reboot:
  become: true
  when: hostname.changed